### ISSUE TITLE
API Call Rate Throttling

### ISSUE THREAD

**Issue by jrudge-kcom** [cfn-sphere/cfn-sphere#113] opened 2016-08-18 08:02 UTC
I have been hitting an issue when syncing a large number of stacks where the maximum API call rate has been exceeded. You may just want to think about some code to back of the call frequency a little.

 18.08.2016 09:00:22 ERROR: An error occurred (Throttling) when calling the DescribeStacks operation: Rate exceeded
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cfn_sphere/cli.py", line 74, in sync
    StackActionHandler(config).create_or_update_stacks()
  File "/usr/local/lib/python2.7/dist-packages/cfn_sphere/**init**.py", line 55, in create_or_update_stacks
    self.cfn.validate_stack_is_ready_for_action(stack)
  File "/usr/local/lib/python2.7/dist-packages/cfn_sphere/aws/cfn.py", line 187, in validate_stack_is_ready_for_action
    if cfn_stack.stack_status not in valid_states:
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 339, in property_loader
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/action.py", line 83, in **call**
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 278, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 572, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (Throttling) when calling the DescribeStacks operation: Rate exceeded
18.08.2016 09:00:22 INFO: Please report at https://github.com/cfn-sphere/cfn-sphere/issues!

**Comment by konz** [comment] 2016-09-19 09:35
What does "large number of stacks" actually mean in absolute numbers? Do you have all the stacks in a single cfn-sphere config? Are there other uses of CloudFormation API at the same time?

**Comment by jrudge-kcom** [comment] 2016-09-20 08:18
We have 20+ in some of the environment definitions. I think it was only around 10 at the time. AWS have the issue well documented.

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html

**Comment by marco-hoyer** [comment] 2016-10-07 13:31
I've wrapped all api calls with the retry handler retrying the call with exponential back off as suggested by aws. This will not prevent throttling to occur but may help to find the root cause. In the supplied example the validate_stack_is_ready_for_action() call fails with throttling exception which doesn't seem to cause it. There might be other calls doing so. I will try to dig deeper into the api requests done by cfn-sphere. Your issue should be fixed by now with the next release.

**Comment by konz** [comment] 2016-10-07 15:42
Boto itself implements backoff and retry, just without much delays. Setting boto and botocore to debug level logging as in PR #121 might help analyzing whats going on.

**Comment by marco-hoyer** [comment] 2016-11-01 12:25
a release is on its way

**Closed by marco-hoyer** 2016-11-01 12:25 UTC
Labels: bug
